---
title: "CUSTOS 2020"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: https://github.com/andreferraribr/custos
    social:
    - twitter
    - facebook
    - menu
runtime: shiny

---





```{r setup, include=FALSE}
options(scipen=999)
options(digits=2)
# options (LC_NUMERIC="pt_BR.UTF-8")
```




```{r libraries,  message=FALSE}
library(flexdashboard)
library(readxl)
library(ggplot2)
library(stringr)
library(plotly)
library(DT)
library(shiny)
library(shinyWidgets)
library(lubridate)
library(tidyverse)
library(janitor)
library(googledrive)
library(gargle)
library(writexl)

```



```{r negar %in%}
# https://www.r-bloggers.com/the-notin-operator/
'%!in%' <- Negate('%in%')
```

```{r função "dados" importar e renomear variaveis}
# funcao para importar dados e renomear variaveis
dados = function(tg, depara){
  # carregar planilha com dados do Tesouro Gerencial (tg)
  df <- read_xlsx(tg)
  # carregar planilha com o de_para dos nomes dos atributos do Tesouro Gerencial para nomes mais amigáveis para as variáveis. Por exemplo, de(Unidade Orçamentária Código) para(uo_cod)
  tg2r <- read_xlsx(depara)
  # renomear as colunas da df fazendo o de_para
  colnames(df)<-tg2r$r_name
  return(df)
}
```

```{r função "tabela" formatar numeros incluir totalizador}
# comentar funcao e parametro para totalizar colunas e linhas
# ajustar formatacao de acordo com a opcao de totalizar
# criar forma melhor para selecionar apenas colunas numericas para formatacao de valor
# coluna = "Total" para totalizar columnwise
tabela = function (df,coluna = NULL) {
      datatable((df)%>%
  # "row" para o total aparecer na linha, ou seja, totalizar os valores de uma coluna
  adorn_totals("row") ,
      filter = 'top',          
      extensions = 'Buttons',
      options = list( 
                  # order = list (df[(length(df))], 'desc'),
                  dom = "Blfrtip",
                  buttons = 
                    list("copy", list(
                      extend = "collection",
                      buttons = c("csv", "excel", "pdf"),
                      text = "Download" ) ),
                  lengthMenu = list( c(-1, 5, 10,20),
                                     c( "tudo",5, 10, 20)),
                  pageLength = -1 )
      )%>%
  formatRound(
  # formatar apenas as colunas numericas.
  # sapply para identificar as colunas numericas e combinar com o parametro COLUNA
    # ((ncol(df %>% select_if(is.character))+1):(ncol(df )+1)),
    # http://datamining.togaware.com/survivor/Remove_Non_Numeric.html
    (c(colnames(df[,sapply(df, is.numeric)]), coluna)),
  digits = 2,
  interval = 3,
  mark = ",",
  dec.mark = getOption("OutDec")
)
}
# mesma lógica da função "tabela", mas com o objetivo de apresentar os números no formato R$
tabela_reais = function (df,coluna = NULL) {
      datatable((df)%>%
  # "row" para o total aparecer na linha, ou seja, totalizar os valores de uma coluna
  adorn_totals("row") ,
      filter = 'top', 
      rownames = FALSE,
      extensions = 'Buttons',
      options = list( 
                  # order = list (df[(length(df))], 'desc'),
                  dom = "Blfrtip",
                  buttons = 
                    list("copy", list(
                      extend = "collection",
                      buttons = c("csv", "excel", "pdf"),
                      text = "Download" ) ),
                  lengthMenu = list( c(-1, 5, 10,20),
                                     c( "tudo",5, 10, 20)),
                  pageLength = -1 )
      )%>%
  formatRound(
  # formatar apenas as colunas numericas.
  # sapply para identificar as colunas numericas e combinar com o parametro COLUNA
    # ((ncol(df %>% select_if(is.character))+1):(ncol(df )+1)),
    # http://datamining.togaware.com/survivor/Remove_Non_Numeric.html
    (c(colnames(df[,sapply(df, is.numeric)]), coluna)),
  digits = 2,
  interval = 3,
  mark = ".",
  dec.mark = ","
) 
}
```



```{r função "reais" para embelezar numeros}
# embelezar o número do value box
reais <- function(numero){
  paste0("R$ ",round(numero/1000,digits = 1), " K")
}
```



```{r}


pessoal <- read_excel("r_pessoal_ME_cargo.xlsx")

uorgs_descentralizadas <- read_excel("uorgs_descentralizadas.xlsx")

pessoal <- pessoal %>%  mutate (tipo_org = if_else(`UORG Código` %in% uorgs_descentralizadas$`UORG Código`, "apoio", "cliente"))

pessoal <- pessoal %>%  mutate (uf = str_sub(pessoal$UPAG, start = -2L, end=-1L))


custo_pessoal <- (pessoal %>% group_by(uf,  tipo_org) %>% summarise(custo_pessoal  =  (sum(`Custo Pessoal - Ativo`)/1000)))

# 
# tabela(pessoal %>% group_by(uf, UPAG, tipo_org) %>% summarise(custo_pessoal  =  (sum(`Custo Pessoal - Ativo`)/1000), pessoal =  format(round(sum(`Força de Trabalho`)/12), nsmall = 0)))
# 
# tabela(pessoal %>% group_by(uf, tipo_org) %>% filter(uf %!in% c("AC","RR","RO","AP", "DF"))%>% summarise(custo_pessoal  =  (sum(`Custo Pessoal - Ativo`)/1000))%>% pivot_wider( names_from = tipo_org, values_from = custo_pessoal) %>% mutate(percentual = apoio/cliente ))

```


```{r}

custos <- read_excel("custos.xlsx")

nomes_atributos <-  read_excel("tg2r_custos_me.xlsx")
colnames(custos) <- nomes_atributos$r_name

ugr_descentralizadas <- read_csv("ugr_descentralizadas.csv")

custos <- custos %>%  mutate(uf =
  case_when(
  ug_emitente == "GERENCIA REG. ADMINISTRACAO DO ME-MATO GROSSO"  ~ "MT", 
  ug_emitente == "GERENCIA REG. DE ADM. DO ME - ESPIRITO SANTO"   ~ "ES",
  ug_emitente == "GERENCIA REG. DE ADMINISTRACAO DO ME - ACRE"    ~ "AC",
  ug_emitente == "GERENCIA REG. DE ADMINISTRACAO DO ME - AMAPA"   ~ "AP",
  ug_emitente == "GERENCIA REG. DE ADMINISTRACAO DO ME - GOIAS"   ~ "GO",
  ug_emitente == "GERENCIA REG. DE ADMINISTRACAO DO ME - PIAUI"   ~ "PI",
  ug_emitente == "GERENCIA REG. DE ADMINISTRACAO DO ME-AMAZONAS"  ~ "AM",
  ug_emitente == "GERENCIA REG. DE ADMINISTRACAO DO ME-RONDONIA"  ~ "RO",
  ug_emitente == "GERENCIA REG.DE ADM.DO ME - SANTA CATARINA"     ~ "SC",
  ug_emitente == "GERENCIA REG.DE ADM.DO ME-MATO GROSSO DO SUL"   ~ "MS",
  ug_emitente == "GERENCIA REG.DE ADM.DO ME-RIO GARNDE DO NORTE"  ~ "RN",
  ug_emitente == "GERENCIA REG.DE ADMINISTRACAO DO ME - ALAGOAS"  ~ "AL",
  ug_emitente == "GERENCIA REG.DE ADMINISTRACAO DO ME - PARAIBA"  ~ "PB",
  ug_emitente == "GERENCIA REG.DE ADMINISTRACAO DO ME - RORAIMA"  ~ "RR",
  ug_emitente == "GERENCIA REG.DE ADMINISTRACAO DO ME - SERGIPE"  ~ "SE",
  ug_emitente == "GERENCIA REG.DE ADMINISTRACAO DO ME-MARANHAO"   ~ "MA",
  ug_emitente == "SUPERINTENDENCIA REG. ADM. DO ME - BAHIA"       ~ "BA",
  ug_emitente == "SUPERINTENDENCIA REG. ADM. DO ME - CEARA"       ~ "CE",
  ug_emitente == "SUPERINTENDENCIA REG. ADM. DO ME - PARA"        ~ "PA",
  ug_emitente == "SUPERINTENDENCIA REG. ADM. DO ME - PARANA"      ~ "PR",
  ug_emitente == "SUPERINTENDENCIA REG. ADM. DO ME - PERNANBUCO"  ~ "PE",
  ug_emitente == "SUPERINTENDENCIA REG. ADM. DO ME - SAO PAULO"   ~ "SP",
  ug_emitente == "SUPERINTENDENCIA REG. ADM. DO ME-MINAS GERAIS"  ~ "MG",
  ug_emitente == "SUPERINTENDENCIA REG.ADM.DO ME-RIO DE JANEIRO"  ~ "RJ",
  ug_emitente == "SUPERINTENDENCIA REG.ADM.DO ME-RIO GRANDE SUL"  ~ "RS",
  TRUE ~ "na"
  )
)


custos <- custos %>% mutate(tipo_org =ifelse( ugr_id %in% ugr_descentralizadas$ugr_id, "apoio","cliente"))

custeio <- (custos %>% group_by(uf, tipo_org)  %>% summarise(custeio  =  (sum(custo)/1000)))

# tg <- (custos %>% group_by(uf, tipo_org, ug_emitente_id)  %>% filter(uf %!in% c("AC","RR","RO","AP", "DF", "na"))%>% summarise(custeio  =  (sum(custo)/1000)))
# tabela(custos %>% group_by(uf, tipo_org) %>% filter (uf != "na",uf %!in% c("AC","RR","RO","AP", "DF") )%>% summarise(custo_apoios  =  (sum(custo)/1000))%>% pivot_wider( names_from = tipo_org, values_from = custo_apoios)  %>% mutate(percentual = apoio/cliente ))

# tabela(custos %>% group_by(uf,ug_emitente, tipo_org,centro_custo ,ndd) %>% filter (uf != "na")%>% summarise(custo_apoios  =  (sum(custo)/1000)))

```
```{r}




custo_apoio <- full_join(custeio %>% filter(tipo_org == "apoio"), custo_pessoal %>% filter(tipo_org == "apoio"), by = c("uf" = "uf",  "tipo_org" = "tipo_org"))

custo_cliente <- full_join(custeio %>% filter(tipo_org == "cliente"), custo_pessoal %>% filter(tipo_org == "cliente"), by = c("uf" = "uf",  "tipo_org" = "tipo_org"))

custo_apoio_reactive <- reactive(custo_apoio %>% filter(if_else( input$uf == "TODOS", uf != "TODOS" , uf == input$uf)))

custo_cliente_reactive <- reactive(custo_cliente %>% filter(if_else( input$uf == "TODOS", uf != "TODOS" , uf == input$uf)))


custo_total <- full_join(custeio, custo_pessoal, by = c("uf" = "uf",  "tipo_org" = "tipo_org"))
custo_total <-  (custo_total %>% group_by(uf, tipo_org) %>% summarise(custo_total  =  (sum(custo_pessoal+ custeio)))%>% pivot_wider( names_from = tipo_org, values_from = custo_total)  %>% mutate(percentual = apoio/cliente )) 



```
```{r}
# ggplot(custo_total %>% filter(tipo_org == "apoio") %>% pivot_longer(cols = c(custo_pessoal, custeio),names_to = "tipo_custo",values_to = "custo"), aes(x = uf, y = custo ,fill = tipo_custo)) + coord_flip()+
    # geom_bar(position = "fill",stat = "identity")




# tabela(custo_total %>% pivot_longer(cols = c(custo_pessoal, custeio),names_to = "tipo custo",values_to = "custo"))
```
```{r}
# ggplot(custo_total %>% filter(tipo_org == "apoio") , aes(x = custo_pessoal, y = custeio)) + 
#     geom_point()
```
```{r eval=FALSE, include=FALSE}

# t_p <- (custo_total %>% group_by(uf, tipo_org) %>% summarise(custo_total  =  (sum(custo_pessoal+ custeio)))%>% pivot_wider( names_from = tipo_org, values_from = custo_total)  %>% mutate(percentual = apoio/cliente ))
# 
# ggplot(t_p   , aes(x = reorder (uf,-percentual), y = percentual))+ coord_flip() + 
#     geom_col()
```

Sidebar {.sidebar}
=====================================


```{r, input$uf}
# input para selecionar a UF
selectInput("uf", label = h3("escolha o Estado:"),
    choices = c (unique(custo_total$uf), "TODOS"),
    selected = "TODOS")


custo_total_reactive <- reactive(custo_total %>% filter( if_else( input$uf == "TODOS", uf != "TODOS" , uf == input$uf)))

```

Unidades Descentralizadas
=============================================






Row 
-----------------------------------------------------------------------



### Custo total



```{r}

renderValueBox({
 valueBox( reais(sum(custo_apoio_reactive()$custo_pessoal)+sum(custo_apoio_reactive()$custeio)),
  color = "red")
  })
```



### Custeio



```{r}

renderValueBox({
 valueBox( reais(sum(custo_apoio_reactive()$custeio)),
  color = "purple")
  })
```

### Custo com Pessoal



```{r}

renderValueBox({
 valueBox( reais(sum(custo_apoio_reactive()$custo_pessoal)),
  color = "#f242f5")
  })
```

### Comissão



```{r}

renderValueBox({
 valueBox( (sum(custo_apoio_reactive()$custeio)+ sum(custo_apoio_reactive()$custo_pessoal))/(sum(custo_cliente_reactive()$custeio)+ sum(custo_cliente_reactive()$custo_pessoal))*100,
           color = "gray")
  })
```







Row 
-----------------------------------------------------------------------


### Ranking custo com pessoal das unidades de apoio



```{r}
renderPlotly( ggplot(custo_cliente   , aes(x = reorder (uf,-custo_pessoal), y = custo_pessoal))+ coord_flip() + 
    geom_col(color = if_else(custo_cliente$uf == input$uf, "red", "grey")))
```



### Ranking custo total das unidades de apoio


```{r}
renderPlotly( ggplot(custo_cliente   , aes(x = reorder (uf,-custeio), y = custeio))+ coord_flip() + 
    geom_col(color = if_else(custo_cliente$uf == input$uf, "red", "grey")))
```


### Ranking custo com pessoal das unidades de apoio



```{r}
renderPlotly( ggplot(custo_cliente   , aes(x = reorder (uf,-custo_pessoal), y = custo_pessoal))+ coord_flip() + 
    geom_col(color = if_else(custo_cliente$uf == input$uf, "red", "grey")))
```



### Ranking comissao


```{r}
renderPlotly( ggplot(custo_total   , aes(x = reorder (uf,-percentual), y = percentual))+ coord_flip() + 
    geom_col(color = if_else(custo_cliente$uf == input$uf, "red", "grey")))
```
